workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Create iOS project if missing
        script: |
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            flutter create --platforms=ios .
          fi
      - name: Set iOS deployment target
        script: |
          if [ -f "ios/Podfile" ]; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/g" ios/Podfile
            sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET'] = '.*'/IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'/g" ios/Podfile
          fi
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Run tests
        script: |
          flutter test || echo "Tests completed with warnings"
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-test-workflow:
    name: iOS Test on Simulator
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Create iOS project if missing
        script: |
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            flutter create --platforms=ios .
          fi
      - name: Set iOS deployment target
        script: |
          if [ -f "ios/Podfile" ]; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/g" ios/Podfile
            sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET'] = '.*'/IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'/g" ios/Podfile
          fi
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Run tests
        script: |
          flutter test || echo "Tests completed with warnings"
      - name: Build for simulator
        script: |
          flutter build ios --simulator --debug
      - name: Verify simulator build
        script: |
          # Verify that the simulator build was successful
          echo "Checking simulator build..."
          
          SIM_APP_PATH="build/ios/iphonesimulator/Runner.app"
          if [ -d "$SIM_APP_PATH" ]; then
            echo "✅ Simulator build successful: $SIM_APP_PATH"
            echo "App size: $(du -sh "$SIM_APP_PATH" | cut -f1)"
            echo "Build verification completed"
          else
            echo "❌ Simulator build not found at $SIM_APP_PATH"
            echo "Checking build directory..."
            find build/ios -name "*.app" -type d 2>/dev/null || echo "No .app files found"
            exit 1
          fi
          
          # Optional: List available simulators for reference
          echo ""
          echo "Available iOS simulators:"
          xcrun simctl list devices available | grep "iPhone" | head -5 || echo "No simulators listed"

  ios-browserstack-workflow:
    name: iOS Build for BrowserStack
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Create iOS project if missing
        script: |
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            flutter create --platforms=ios .
          fi
      - name: Set iOS deployment target
        script: |
          if [ -f "ios/Podfile" ]; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/g" ios/Podfile
            sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET'] = '.*'/IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'/g" ios/Podfile
          fi
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Build IPA for BrowserStack
        script: |
          # Build IPA without code signing (for testing on BrowserStack)
          flutter build ipa --release --no-codesign
          
          # Also create .app bundle for alternative upload
          flutter build ios --release --no-codesign
          
          echo "✅ Build completed"
          echo "IPA location: build/ios/ipa/*.ipa"
          echo "APP location: build/ios/iphoneos/Runner.app"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
